///|/ Copyright (c) Prusa Research 2020 - 2023 Tomáš Mészáros @tamasmeszaros, Lukáš Matěna @lukasmatena
///|/
///|/ PrusaSlicer is released under the terms of the AGPLv3 or higher
///|/
#ifndef SLA_SUPPORTPOINT_HPP
#define SLA_SUPPORTPOINT_HPP

#include <libslic3r/Point.hpp>

#include <cmath>

namespace Slic3r::sla {

// An enum to keep track of where the current points on the ModelObject came from.
enum class PointsStatus {
    NoPoints,           // No points were generated so far.
    Generating,     // The autogeneration algorithm triggered, but not yet finished.
    AutoGenerated,  // Points were autogenerated (i.e. copied from the backend).
    UserModified    // User has done some edits.
};

// Reason of automatic support placement usage
enum class SupportPointType {
    manual_add,
    island, // no move, island should be grouped
    slope,
    //thin,
    //stability,
    //edge
};

// Sentinel for the six extension size fields below: "not set, fall back to the
// global setting". The value itself is the flag - there is no companion
// "is_set" member to keep in sync.
//
// This applies to the six fields introduced for per-point sizing ONLY. It does
// NOT apply to head_front_radius, which predates them: there -1 already means
// "marked for erase" in prepare_permanent_support_points()
// (SLAPrintSteps.cpp), so treating it as "unset" would silently delete points.
inline constexpr float support_point_unset = -1.f;

// Degrees -> radians, spelled out so this header does not depend on M_PI being
// visible (MSVC only defines it under _USE_MATH_DEFINES).
inline constexpr double support_point_deg_to_rad = 3.14159265358979323846 / 180.;

/// <summary>
/// Stereolithography(SLA) support point
/// </summary>
struct SupportPoint
{
    // Position on model surface
    Vec3f pos = Vec3f::Zero(); // [in mm]

    // radius of the touching interface
    // Also define force it must keep
    //
    // Always a real value, never a sentinel: it is set by the point generator
    // and by every importer. It is deliberately NOT part of the
    // support_point_unset scheme used by the six fields below, because
    // prepare_permanent_support_points() (SLAPrintSteps.cpp) already uses -1
    // here to mean "marked for erase" and drops such points. Anything filling
    // a SupportPoint - the JSON import path included - must write a resolved
    // radius into this field, never -1.
    float head_front_radius = 0.f; // [in mm]

    // type
    SupportPointType type{SupportPointType::manual_add};

    // ---- Per-point support geometry ------------------------------------
    // Six extension size fields, on top of head_front_radius above. All are
    // absolute millimetres (degrees for the angle) and are never scaled with
    // the model.
    //
    // Resolution rule for these six: >= 0 means "use this point's own value",
    // < 0 (the support_point_unset sentinel) means "fall back to the global
    // setting". Use the point_*() helpers below rather than open-coding the
    // comparison. The rule never looks at SupportPointType - an autogenerated
    // island/slope point honours a custom size exactly like a manually added
    // one.
    //
    // New fields are appended at the end so that existing aggregate
    // initialisation and positional construction keep working.

    // Radius of the back sphere of the pinhead. Also determines the radius of
    // the pillar grown from this head.
    float head_back_radius_mm = support_point_unset; // [in mm]

    // Distance from the back sphere centre to the front sphere centre.
    float head_width_mm = support_point_unset; // [in mm]

    // How deep the pinhead penetrates the model surface.
    float head_penetration_mm = support_point_unset; // [in mm]

    // Radius of the contact sphere. Tri-state, and the only field where 0 is a
    // real value: < 0 = not set (use the global setting), == 0 = this point
    // explicitly uses no contact sphere, > 0 = the radius. Never test this
    // field with "<= 0" - that would silently turn "off" into "not set".
    //
    // Reserved in this fork: there is no contact-sphere geometry and no global
    // contact-sphere setting here, so nothing consumes this value yet. It is
    // carried through the interchange format and the resolver so a value set
    // by a caller survives a round trip unchanged.
    float contact_sphere_radius = support_point_unset; // [in mm]

    // Radius of the pillar base cone.
    float base_radius_mm = support_point_unset; // [in mm]

    // Bracing angle for the struts/junctions grown from this point. Stored in
    // degrees; SupportTreeConfig::bridge_slope is radians, so convert through
    // point_bracing_angle_rad().
    float support_bracing_angle_deg = support_point_unset; // [in degrees]

    // Which way the pinhead points, away from the surface.
    //
    // Normally the engine works this out from the surface normal and then
    // searches around it for an angle that clears the model. A caller that is
    // placing supports by hand may want the head somewhere that search would
    // never choose: dragging a support moves the PILLAR while the tip stays in
    // the model, so the head has to stretch and lean to bridge the gap.
    //
    // The zero vector is the sentinel for "not set" - a direction has to point
    // somewhere, so no real value can collide with it. Set together with
    // head_width_mm, which sets how far along this direction the junction sits.
    Vec3f head_dir = Vec3f::Zero();

    bool is_island() const { return type == SupportPointType::island; }
    template<class Archive> void serialize(Archive &ar){
        // Every size field must be listed here: a field left out is silently
        // dropped on every cereal round trip (undo/redo, backend snapshots).
        ar(pos, head_front_radius, type,
           head_back_radius_mm, head_width_mm, head_penetration_mm,
           contact_sphere_radius, base_radius_mm, support_bracing_angle_deg,
           head_dir);
    }

    // unsaved changes + cache invalidation
    bool operator==(const SupportPoint &sp) const {
        // Every size field must be compared here as well: a field left out
        // makes change detection miss an edit and reuse a stale support tree.
        auto same = [](float a, float b) { return std::abs(a - b) < float(EPSILON); };
        return pos == sp.pos && type == sp.type &&
               same(head_front_radius, sp.head_front_radius) &&
               same(head_back_radius_mm, sp.head_back_radius_mm) &&
               same(head_width_mm, sp.head_width_mm) &&
               same(head_penetration_mm, sp.head_penetration_mm) &&
               same(contact_sphere_radius, sp.contact_sphere_radius) &&
               same(base_radius_mm, sp.base_radius_mm) &&
               same(support_bracing_angle_deg, sp.support_bracing_angle_deg) &&
               head_dir == sp.head_dir;
    }

    bool operator!=(const SupportPoint &sp) const { return !(sp == (*this)); }

};
using SupportPoints = std::vector<SupportPoint>;

// ---------------------------------------------------------------------------
// Per-point geometry resolution
//
// One place decides "custom value or global default" for the six extension
// size fields, so no call site has to re-derive the rule. Every function here
// is pure: it reads the point and the global default and returns a value.
//
// head_front_radius has no resolver here on purpose - see the field comment:
// it always carries a real value, and -1 means something else entirely.
// ---------------------------------------------------------------------------

// Does one of the six extension fields carry a custom value?
//
// The test is ">= 0", not "> 0". contact_sphere_radius uses 0 as a real value
// ("no contact sphere on this point"), so a "<= 0 means unset" test would
// silently discard it. Nothing here looks at SupportPointType.
inline bool point_field_is_set(float v) { return v >= 0.f; }

// Generic resolver: the point's own value when set, the global default
// otherwise.
inline double point_resolve(float v, double global_default)
{
    return point_field_is_set(v) ? double(v) : global_default;
}

inline double point_head_back_radius_mm(const SupportPoint &sp, double global_mm)
{
    return point_resolve(sp.head_back_radius_mm, global_mm);
}

inline double point_head_width_mm(const SupportPoint &sp, double global_mm)
{
    return point_resolve(sp.head_width_mm, global_mm);
}

/**
 * Whether this point dictates which way its head points.
 * @param sp the support point
 * @returns true when the caller set a direction
 */
inline bool point_has_head_dir(const SupportPoint &sp)
{
    return sp.head_dir.squaredNorm() > EPSILON;
}

inline double point_head_penetration_mm(const SupportPoint &sp, double global_mm)
{
    return point_resolve(sp.head_penetration_mm, global_mm);
}

inline double point_base_radius_mm(const SupportPoint &sp, double global_mm)
{
    return point_resolve(sp.base_radius_mm, global_mm);
}

// The field is stored in degrees, SupportTreeConfig::bridge_slope is radians.
// Both the conversion and the fallback live here so no call site mixes units.
inline double point_bracing_angle_rad(const SupportPoint &sp, double global_rad)
{
    return point_field_is_set(sp.support_bracing_angle_deg)
               ? double(sp.support_bracing_angle_deg) * support_point_deg_to_rad
               : global_rad;
}

// The three meanings of contact_sphere_radius.
enum class ContactSphereState {
    UseGlobalDefault, // < 0  : not set
    Disabled,         // == 0 : this point explicitly has no contact sphere
    Custom            // > 0  : this value is the radius
};

inline ContactSphereState point_contact_sphere_state(const SupportPoint &sp)
{
    // Three mutually exclusive branches on purpose. Collapsing the first two
    // into "<= 0" is exactly the bug this function exists to prevent, so the
    // zero case is tested for equality rather than folded into the sign test.
    if (sp.contact_sphere_radius < 0.f)
        return ContactSphereState::UseGlobalDefault;
    if (sp.contact_sphere_radius == 0.f)
        return ContactSphereState::Disabled;
    return ContactSphereState::Custom;
}

// Resolved contact sphere: whether to build one at all, and its radius.
//
// No caller in this fork yet: there is no contact-sphere geometry and no
// global contact-sphere setting to pass in. The resolver exists so the
// tri-state has one definition the day one appears.
struct ContactSphere {
    bool   enabled   = false;
    double radius_mm = 0.;
};

inline ContactSphere point_contact_sphere(const SupportPoint &sp,
                                          bool               global_enabled,
                                          double             global_radius_mm)
{
    switch (point_contact_sphere_state(sp)) {
    case ContactSphereState::Disabled:
        return ContactSphere{false, 0.};
    case ContactSphereState::Custom:
        return ContactSphere{true, double(sp.contact_sphere_radius)};
    case ContactSphereState::UseGlobalDefault:
    default:
        return ContactSphere{global_enabled, global_radius_mm};
    }
}

} // namespace Slic3r::sla

#endif // SUPPORTPOINT_HPP
